version: '3'

services:
  api:
    container_name: fullrss_api
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    env_file:
      - db.env
      - config.env
    ports:
      - 8080:8080
    tty:
      true
    volumes:
      - ./data/api:/go/src/api
    depends_on:
      - postgres
    command: bin/sh -c "./wait.sh realize start --run"

  postgres: # 起動コンテナを区別する名称。コンテナネットワーク上でのホスト名になる
    container_name: fullrss_db
    image: postgres:12.4-alpine # ここでDockerHubから取得したいイメージ:タグを指定する
    env_file:
      - db.env
    ports:
      - 5432:5432 # ポート転送の設定 ... ホスト側ポート:コンテナ内ポート
    volumes: # マウントの設定 ... ホスト側ディレクトリ:コンテナ側ディレクトリ
      - ./data/db/sh:/docker-entrypoint-initdb.d # この中の.sh、.sqlファイルは自動実行される
      - ./data/db/storage:/var/lib/postgresql/data # データベースデータを永続化する

  node:
    container_name: fullrss_app
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - config.env
    volumes:
     - ./data/react/app:/usr/src/app
    command: sh -c "cd full-rss-generator && yarn start"
    ports:
     - "3000:3000"
    tty: true
    depends_on:
     - api

  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - config.env
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/nginx/htpasswd:/etc/nginx/htpasswd
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: /bin/sh -c "envsubst '$$APP_CONTAINER$$DOMAIN_NAME$$API_CONTAINER' < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/app.conf && while :; do sleep 6h & wait $${!}; nginx -s reload; done && nginx -g 'daemon off;'"
    depends_on:
      - node
      - api

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx
